### ISSUE TITLE
Any posibility to make the role idempotent ?

### ISSUE THREAD

**Issue by yodatak** [danielkoster/ansible-role-transmission-daemon#14]
Hi is there is a may to make the role idempotent.
this task is not :
*  => danielkoster.transmission-daemon : transmission-daemon | Create settings file
Because of the password i think

**Comment by yodatak** [comment]
Hum seem complicated to do https://github.com/transmission/transmission/issues/839

**Comment by danielkoster** [comment]
Hi! The role is idem potent, I have a unit test to ensure this. Your setting probably gets overridden by transmission because of the hashing. If you provide a password hash, as is provided in the default variables, this will probably be resolved.

See:
https://github.com/danielkoster/ansible-role-transmission-daemon/blob/ad91e8420c754fdeaf340e9160a8d259644e4f4a/defaults/main.yml#L51

What you can do is set your password in the settings, run ansible, then retrieve the hashed password from your transmission settings file, and set that hash as your password for this role. That way it's idempotent again. Let me know if this works out for you!

**Comment by yodatak** [comment]
Thanks its fix the issue !
